apiVersion: v1
kind: Pod
metadata:
  name: vecro-mongodb-test
spec:
  containers:
  - name: mongodb
    image: mongo:4.2
    env:
    - name: MONGO_INITDB_ROOT_USERNAME
      value: 'root'
    - name: MONGO_INITDB_ROOT_PASSWORD
      value: 'password'
    - name: MONGO_INITDB_DATABASE
      value: 'data'
    volumeMounts:
    - name: init-script
      mountPath: /docker-entrypoint-initdb.d/mongo-init.js
    ports:
    - containerPort: 27017
  - name: vecro-mongodb
    image: vecro-mongodb:v1
    env:
    - name: VECRO_DB_READ_OPS
      value: '0'
    - name: VECRO_DB_WRITE_OPS
      value: '10'
  volumes:
  - name: init-script
    configMap:
      name: mongo-initjs

